#!/bin/bash
# Script to organize remaining examples into subdirectories
# This is a planning document showing the new structure

echo "Example Migration Plan"
echo "====================="
echo ""
echo "✅ COMPLETED:"
echo "  basics/model_definition.py (from 01_basic_model_definition.py)"
echo "  training/vision_mnist.py (from 05_vision_training_mnist.py)"
echo ""
echo "📋 TO MIGRATE:"
echo ""
echo "Basics (examples 01-04):"
echo "  02 → basics/save_load_model.py"
echo "  03 → basics/data_loading_tfds.py"
echo "  04 → basics/data_loading_grain.py"
echo ""
echo "Training (examples 05-06):"
echo "  06 → training/language_model.py"
echo ""
echo "Export (example 07):"
echo "  07 → export/model_formats.py"
echo ""
echo "Integrations (examples 08-10):"
echo "  08 → integrations/huggingface.py"
echo "  09 → integrations/resnet_streaming.py"
echo "  10 → integrations/wandb.py"
echo ""
echo "Advanced (examples 11-15):"
echo "  11 → advanced/bert_fineweb.py"
echo "  12 → advanced/gpt_training.py"
echo "  13 → advanced/simclr_contrastive.py"
echo "  14 → advanced/maml_metalearning.py"
echo "  15 → advanced/knowledge_distillation.py"
echo ""
echo "Distributed (examples 16-19):"
echo "  16 → distributed/data_parallel_pmap.py"
echo "  17 → distributed/sharding_spmd.py"
echo "  18 → distributed/pipeline_parallel.py"
echo "  19 → distributed/fsdp_sharding.py"
echo ""
echo "Note: Original files remain in examples/ root for backward compatibility"
echo "New modular versions use shared components and have tests"
